version: '3'
services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes: 
     - jenkins:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
     - "80:80"
volumes: 
  jenkins:
