version: '3'
services:
  jenkins:
    container_name: jenkins
    build: ./jenkins    
    volumes: 
     - jenkins:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
  jenkins-docker:
    build: ./jenkins/docker-slave
    depends_on:
      - "jenkins"
    command: ["./wait-for-it.sh", "jenkins:8080", "--", "jenkins-slave"]
    environment:
     - JENKINS_URL=jenkins:8080
     - JENKINS_AGENT_NAME=jenkins-docker
  nginx:
    container_name: nginx    
    build: ./nginx
    ports:
     - "80:80"
     - "443:443"
volumes: 
  jenkins:
